/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.mobilebasicsanity.wmstudio.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.manager.ExportedFileManager;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.tools.api.core.annotations.MapTo;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.mobilebasicsanity.wmstudio.Employee1;
import com.mobilebasicsanity.wmstudio.Employee1Id;
import com.mobilebasicsanity.wmstudio.service.Employee1Service;


/**
 * Controller object for domain model class Employee1.
 * @see Employee1
 */
@RestController("WMSTUDIO.Employee1Controller")
@Api(value = "Employee1Controller", description = "Exposes APIs to work with Employee1 resource.")
@RequestMapping("/WMSTUDIO/Employee1")
public class Employee1Controller {

    private static final Logger LOGGER = LoggerFactory.getLogger(Employee1Controller.class);

    @Autowired
	@Qualifier("WMSTUDIO.Employee1Service")
	private Employee1Service employee1Service;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new Employee1 instance.")
    @RequestMapping(method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Employee1 createEmployee1(@RequestBody Employee1 employee1) {
		LOGGER.debug("Create Employee1 with information: {}" , employee1);

		employee1 = employee1Service.create(employee1);
		LOGGER.debug("Created Employee1 with information: {}" , employee1);

	    return employee1;
	}

    @ApiOperation(value = "Returns the Employee1 instance associated with the given composite-id.")
    @RequestMapping(value = "/composite-id", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Employee1 getEmployee1(@RequestParam("eid") Integer eid, @RequestParam("username") String username, @RequestParam("city") String city, @RequestParam("street") String street, @RequestParam("jobtitle") String jobtitle, @RequestParam("lastname") String lastname, @RequestParam("firstname") String firstname, @RequestParam("password") String password, @RequestParam("role") String role) {

        Employee1Id employee1Id = new Employee1Id();
        employee1Id.setEid(eid);
        employee1Id.setUsername(username);
        employee1Id.setCity(city);
        employee1Id.setStreet(street);
        employee1Id.setJobtitle(jobtitle);
        employee1Id.setLastname(lastname);
        employee1Id.setFirstname(firstname);
        employee1Id.setPassword(password);
        employee1Id.setRole(role);

        LOGGER.debug("Getting Employee1 with id: {}" , employee1Id);
        Employee1 employee1 = employee1Service.getById(employee1Id);
        LOGGER.debug("Employee1 details with id: {}" , employee1);

        return employee1;
    }



    @ApiOperation(value = "Updates the Employee1 instance associated with the given composite-id.")
    @RequestMapping(value = "/composite-id", method = RequestMethod.PUT)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Employee1 editEmployee1(@RequestParam("eid") Integer eid, @RequestParam("username") String username, @RequestParam("city") String city, @RequestParam("street") String street, @RequestParam("jobtitle") String jobtitle, @RequestParam("lastname") String lastname, @RequestParam("firstname") String firstname, @RequestParam("password") String password, @RequestParam("role") String role, @RequestBody Employee1 employee1) {

        employee1.setEid(eid);
        employee1.setUsername(username);
        employee1.setCity(city);
        employee1.setStreet(street);
        employee1.setJobtitle(jobtitle);
        employee1.setLastname(lastname);
        employee1.setFirstname(firstname);
        employee1.setPassword(password);
        employee1.setRole(role);

        LOGGER.debug("Employee1 details with id is updated with: {}" , employee1);

        return employee1Service.update(employee1);
    }

	@ApiOperation(value = "Partially updates the  Employee1 instance associated with the given composite-id.")
	@RequestMapping(value = "/composite-id", method = RequestMethod.PATCH)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Employee1 patchEmployee1(@RequestParam("eid") Integer eid, @RequestParam("username") String username, @RequestParam("city") String city, @RequestParam("street") String street, @RequestParam("jobtitle") String jobtitle, @RequestParam("lastname") String lastname, @RequestParam("firstname") String firstname, @RequestParam("password") String password, @RequestParam("role") String role, @RequestBody @MapTo(Employee1.class) Map<String, Object> employee1Patch) {

        Employee1Id employee1Id = new Employee1Id();
        employee1Id.setEid(eid);
        employee1Id.setUsername(username);
        employee1Id.setCity(city);
        employee1Id.setStreet(street);
        employee1Id.setJobtitle(jobtitle);
        employee1Id.setLastname(lastname);
        employee1Id.setFirstname(firstname);
        employee1Id.setPassword(password);
        employee1Id.setRole(role);
        LOGGER.debug("Partially updating Employee1 with id: {}" , employee1Id);

        Employee1 employee1 = employee1Service.partialUpdate(employee1Id, employee1Patch);
        LOGGER.debug("Employee1 details after partial update: {}" , employee1);

        return employee1;
    }


    @ApiOperation(value = "Deletes the Employee1 instance associated with the given composite-id.")
    @RequestMapping(value = "/composite-id", method = RequestMethod.DELETE)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteEmployee1(@RequestParam("eid") Integer eid, @RequestParam("username") String username, @RequestParam("city") String city, @RequestParam("street") String street, @RequestParam("jobtitle") String jobtitle, @RequestParam("lastname") String lastname, @RequestParam("firstname") String firstname, @RequestParam("password") String password, @RequestParam("role") String role) {

        Employee1Id employee1Id = new Employee1Id();
        employee1Id.setEid(eid);
        employee1Id.setUsername(username);
        employee1Id.setCity(city);
        employee1Id.setStreet(street);
        employee1Id.setJobtitle(jobtitle);
        employee1Id.setLastname(lastname);
        employee1Id.setFirstname(firstname);
        employee1Id.setPassword(password);
        employee1Id.setRole(role);

        LOGGER.debug("Deleting Employee1 with id: {}" , employee1Id);
        Employee1 employee1 = employee1Service.delete(employee1Id);

        return employee1 != null;
    }


    /**
     * @deprecated Use {@link #findEmployee1s(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of Employee1 instances matching the search criteria.")
    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Employee1> searchEmployee1sByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Employee1s list by query filter:{}", (Object) queryFilters);
        return employee1Service.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Employee1 instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @RequestMapping(method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Employee1> findEmployee1s(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Employee1s list by filter:", query);
        return employee1Service.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Employee1 instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @RequestMapping(value="/filter", method = RequestMethod.POST, consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Employee1> filterEmployee1s(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Employee1s list by filter", query);
        return employee1Service.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param.")
    @RequestMapping(value = "/export/{exportType}", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportEmployee1s(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return employee1Service.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @RequestMapping(value = "/export", method = {RequestMethod.POST}, consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportEmployee1sAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = Employee1.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> employee1Service.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of Employee1 instances matching the optional query (q) request param.")
	@RequestMapping(value = "/count", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countEmployee1s( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting Employee1s");
		return employee1Service.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@RequestMapping(value = "/aggregations", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getEmployee1AggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return employee1Service.getAggregatedValues(aggregationInfo, pageable);
    }


    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service Employee1Service instance
	 */
	protected void setEmployee1Service(Employee1Service service) {
		this.employee1Service = service;
	}

}