/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.mobilebasicsanity.wmstudio.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.math.BigInteger;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.manager.ExportedFileManager;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.tools.api.core.annotations.MapTo;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.mobilebasicsanity.wmstudio.Nopk;
import com.mobilebasicsanity.wmstudio.service.NopkService;


/**
 * Controller object for domain model class Nopk.
 * @see Nopk
 */
@RestController("WMSTUDIO.NopkController")
@Api(value = "NopkController", description = "Exposes APIs to work with Nopk resource.")
@RequestMapping("/WMSTUDIO/Nopk")
public class NopkController {

    private static final Logger LOGGER = LoggerFactory.getLogger(NopkController.class);

    @Autowired
	@Qualifier("WMSTUDIO.NopkService")
	private NopkService nopkService;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new Nopk instance.")
    @RequestMapping(method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Nopk createNopk(@RequestBody Nopk nopk) {
		LOGGER.debug("Create Nopk with information: {}" , nopk);

		nopk = nopkService.create(nopk);
		LOGGER.debug("Created Nopk with information: {}" , nopk);

	    return nopk;
	}

    @ApiOperation(value = "Returns the Nopk instance associated with the given id.")
    @RequestMapping(value = "/{column1:.+}", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Nopk getNopk(@PathVariable("column1") BigInteger column1) {
        LOGGER.debug("Getting Nopk with id: {}" , column1);

        Nopk foundNopk = nopkService.getById(column1);
        LOGGER.debug("Nopk details with id: {}" , foundNopk);

        return foundNopk;
    }

    @ApiOperation(value = "Updates the Nopk instance associated with the given id.")
    @RequestMapping(value = "/{column1:.+}", method = RequestMethod.PUT)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Nopk editNopk(@PathVariable("column1") BigInteger column1, @RequestBody Nopk nopk) {
        LOGGER.debug("Editing Nopk with id: {}" , nopk.getColumn1());

        nopk.setColumn1(column1);
        nopk = nopkService.update(nopk);
        LOGGER.debug("Nopk details with id: {}" , nopk);

        return nopk;
    }
    
    @ApiOperation(value = "Partially updates the Nopk instance associated with the given id.")
    @RequestMapping(value = "/{column1:.+}", method = RequestMethod.PATCH)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Nopk patchNopk(@PathVariable("column1") BigInteger column1, @RequestBody @MapTo(Nopk.class) Map<String, Object> nopkPatch) {
        LOGGER.debug("Partially updating Nopk with id: {}" , column1);

        Nopk nopk = nopkService.partialUpdate(column1, nopkPatch);
        LOGGER.debug("Nopk details after partial update: {}" , nopk);

        return nopk;
    }

    @ApiOperation(value = "Deletes the Nopk instance associated with the given id.")
    @RequestMapping(value = "/{column1:.+}", method = RequestMethod.DELETE)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteNopk(@PathVariable("column1") BigInteger column1) {
        LOGGER.debug("Deleting Nopk with id: {}" , column1);

        Nopk deletedNopk = nopkService.delete(column1);

        return deletedNopk != null;
    }

    /**
     * @deprecated Use {@link #findNopks(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of Nopk instances matching the search criteria.")
    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Nopk> searchNopksByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Nopks list by query filter:{}", (Object) queryFilters);
        return nopkService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Nopk instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @RequestMapping(method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Nopk> findNopks(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Nopks list by filter:", query);
        return nopkService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Nopk instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @RequestMapping(value="/filter", method = RequestMethod.POST, consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Nopk> filterNopks(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Nopks list by filter", query);
        return nopkService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param.")
    @RequestMapping(value = "/export/{exportType}", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportNopks(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return nopkService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @RequestMapping(value = "/export", method = {RequestMethod.POST}, consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportNopksAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = Nopk.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> nopkService.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of Nopk instances matching the optional query (q) request param.")
	@RequestMapping(value = "/count", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countNopks( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting Nopks");
		return nopkService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@RequestMapping(value = "/aggregations", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getNopkAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return nopkService.getAggregatedValues(aggregationInfo, pageable);
    }


    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service NopkService instance
	 */
	protected void setNopkService(NopkService service) {
		this.nopkService = service;
	}

}