/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.mobilebasicsanity.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class Employee1Id implements Serializable {

    private Integer eid;
    private String username;
    private String city;
    private String street;
    private String jobtitle;
    private String lastname;
    private String firstname;
    private String password;
    private String role;

    public Integer getEid() {
        return this.eid;
    }

    public void setEid(Integer eid) {
        this.eid = eid;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getStreet() {
        return this.street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getJobtitle() {
        return this.jobtitle;
    }

    public void setJobtitle(String jobtitle) {
        this.jobtitle = jobtitle;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Employee1)) return false;
        final Employee1 employee1 = (Employee1) o;
        return Objects.equals(getEid(), employee1.getEid()) &&
                Objects.equals(getUsername(), employee1.getUsername()) &&
                Objects.equals(getCity(), employee1.getCity()) &&
                Objects.equals(getStreet(), employee1.getStreet()) &&
                Objects.equals(getJobtitle(), employee1.getJobtitle()) &&
                Objects.equals(getLastname(), employee1.getLastname()) &&
                Objects.equals(getFirstname(), employee1.getFirstname()) &&
                Objects.equals(getPassword(), employee1.getPassword()) &&
                Objects.equals(getRole(), employee1.getRole());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEid(),
                getUsername(),
                getCity(),
                getStreet(),
                getJobtitle(),
                getLastname(),
                getFirstname(),
                getPassword(),
                getRole());
    }
}