/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.mobilebasicsanity.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

public class IncludeId implements Serializable {

    private BigInteger id;
    private String firstName;
    private Double salary;
    private BigInteger salary2;

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public Double getSalary() {
        return this.salary;
    }

    public void setSalary(Double salary) {
        this.salary = salary;
    }

    public BigInteger getSalary2() {
        return this.salary2;
    }

    public void setSalary2(BigInteger salary2) {
        this.salary2 = salary2;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Include)) return false;
        final Include include = (Include) o;
        return Objects.equals(getId(), include.getId()) &&
                Objects.equals(getFirstName(), include.getFirstName()) &&
                Objects.equals(getSalary(), include.getSalary()) &&
                Objects.equals(getSalary2(), include.getSalary2());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getFirstName(),
                getSalary(),
                getSalary2());
    }
}