/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.mobilebasicsanity.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

public class JobHistoryId implements Serializable {

    private Integer employeeId;
    private LocalDateTime startDate;

    public Integer getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    public LocalDateTime getStartDate() {
        return this.startDate;
    }

    public void setStartDate(LocalDateTime startDate) {
        this.startDate = startDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof JobHistory)) return false;
        final JobHistory jobHistory = (JobHistory) o;
        return Objects.equals(getEmployeeId(), jobHistory.getEmployeeId()) &&
                Objects.equals(getStartDate(), jobHistory.getStartDate());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmployeeId(),
                getStartDate());
    }
}