/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.mobilebasicsanity.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nopk generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`NOPK`")
public class Nopk implements Serializable {

    private BigInteger column1;

    @Id
    @Column(name = "`COLUMN1`", nullable = true, scale = 0, precision = 38)
    public BigInteger getColumn1() {
        return this.column1;
    }

    public void setColumn1(BigInteger column1) {
        this.column1 = column1;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Nopk)) return false;
        final Nopk nopk = (Nopk) o;
        return Objects.equals(getColumn1(), nopk.getColumn1());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getColumn1());
    }
}