/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.mobilebasicsanity.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Regions generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`REGIONS`")
public class Regions implements Serializable {

    private BigInteger regionId;
    private String regionName;

    @Id
    @Column(name = "`REGION_ID`", nullable = false, scale = 0, precision = 38)
    public BigInteger getRegionId() {
        return this.regionId;
    }

    public void setRegionId(BigInteger regionId) {
        this.regionId = regionId;
    }

    @Column(name = "`REGION_NAME`", nullable = true, length = 25)
    public String getRegionName() {
        return this.regionName;
    }

    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Regions)) return false;
        final Regions regions = (Regions) o;
        return Objects.equals(getRegionId(), regions.getRegionId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getRegionId());
    }
}